# h2 DB, 웹 콘솔 접근 허용
spring:
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: 'true'
# 이쁘게 보여주기
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
# DB URL 고정 설정
# 유니크 URL 생성 X
  datasource:
    generate-unique-name: 'false'
    #고정 url 설정
    url: jdbc:h2:mem:testdb
#    # PostgreSQL 연동
#    url: jdbc:postgresql://localhost:5432/firstproject_db
#    username: postgres
#    password: postgres
#    data: classpath:/data.sql
#    initialization-mode: never



# JPA 로깅 설정
# 디버그 레벨로 쿼리 출력
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
# 파라미터 보여주기
        type:
          descriptor:
            sql:
              BasicBinder: TRACE





